[profile.default]
evm_version = "paris"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
solc_args = ["--error-revert", "--revert-strings", "debug", "--warnings"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
